First commit for Homework 3
renvars/home-exercises-java pull request #3
Opened 2022-09-21 18:10 UTC by renvars

2022-10-21 17:50 UTC, NilsKula requested changes

2022-10-21 17:50 UTC, NilsKula commented on Java-Majasdarbi/src/io/codelex/arrays/practice/Hangman.java
> +    private final static String[] words = {
konstantes upercase

2022-10-21 17:50 UTC, NilsKula commented on Java-Majasdarbi/src/io/codelex/arrays/practice/Hangman.java
> +    public static boolean checkIfContainsLetter(char[] word, char letter) {
private

2022-10-21 17:50 UTC, NilsKula commented on Java-Majasdarbi/src/io/codelex/arrays/practice/TicTacToe.java
> +    public static void play() {
private

2022-10-21 17:50 UTC, NilsKula commented on Java-Majasdarbi/src/io/codelex/arrays/practice/TicTacToe.java
> +        if (moveArray[0][0] == player && moveArray[0][1] == player && moveArray[0][2] == player) {
varētu apvienot ar || vai `else if`

2022-10-21 17:50 UTC, NilsKula commented on Java-Majasdarbi/src/io/codelex/classesandobjects/practice/car/Car.java
> +        return fuel > 15;
konstante

2022-10-21 17:50 UTC, NilsKula commented on Java-Majasdarbi/src/io/codelex/classesandobjects/practice/car/Car.java
> +
:thinking:

2022-10-21 17:50 UTC, NilsKula commented on Java-Majasdarbi/src/io/codelex/classesandobjects/practice/car/LitersPerKilometer.java
> +    public static Car getReading(Scanner scan) {
nedaudz missleading nosaukums, jo taisi jaunu mašīnas objektu nevis tikai lasi kādus datus

2022-10-21 17:50 UTC, NilsKula commented on Java-Majasdarbi/src/io/codelex/classesandobjects/practice/dog/Dog.java
> +        if (this.mother.equals(otherDog.mother)) {
`return this.mother.equals(otherDog.mother)`

2022-10-21 17:50 UTC, NilsKula commented on Java-Majasdarbi/src/io/codelex/classesandobjects/practice/gaugeandodo/FuelGauge.java
> +        if (this.liters < 70) {
konstante

2022-10-21 17:50 UTC, NilsKula commented on Java-Majasdarbi/src/io/codelex/classesandobjects/practice/gaugeandodo/FuelGauge.java
> +    int liters;
private

2022-10-27 11:07 UTC, renvars commented
Sorry par 3 commitiem, sākumā likās, ka nesapratu ko darīt ar tām konstantēm un FillUp metodi, bet pēc tam viss aizgāja (cerams pareizi)
Šādā situācijā, var kaut kā tos 3 commitus vienā saspiest, lai nav jāpārbauda visi trīs atsevišķi?

2022-10-27 14:26 UTC, NilsKula approved these changes
no commit daudzuma notiekti nevajag baidīties
un ar to viss ir ok, var izvēlēties vienkārši lai rāda izmaiņas no pēdejā attiecībā pret jebkuru vietu un tad visas izmaiņas varēs redzet vienalicīgi :+1:

2022-10-31 18:33 UTC, merged